# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.group = QtWidgets.QComboBox(self.centralwidget)
        self.group.setObjectName("group")
        self.group.addItem("")
        self.group.setItemText(0, "")
        self.group.addItem("")
        self.verticalLayout.addWidget(self.group)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.SWPEmpty = QtWidgets.QWidget()
        self.SWPEmpty.setObjectName("SWPEmpty")
        self.formLayout = QtWidgets.QFormLayout(self.SWPEmpty)
        self.formLayout.setObjectName("formLayout")
        self.stackedWidget.addWidget(self.SWPEmpty)
        self.SWPVizitki = QtWidgets.QWidget()
        self.SWPVizitki.setObjectName("SWPVizitki")
        self.formLayout_2 = QtWidgets.QFormLayout(self.SWPVizitki)
        self.formLayout_2.setObjectName("formLayout_2")
        self.vizitka_papre_label = QtWidgets.QLabel(self.SWPVizitki)
        self.vizitka_papre_label.setObjectName("vizitka_papre_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.vizitka_papre_label)
        self.vizitka_paper = QtWidgets.QComboBox(self.SWPVizitki)
        self.vizitka_paper.setObjectName("vizitka_paper")
        self.vizitka_paper.addItem("")
        self.vizitka_paper.addItem("")
        self.vizitka_paper.addItem("")
        self.vizitka_paper.addItem("")
        self.vizitka_paper.addItem("")
        self.vizitka_paper.addItem("")
        self.vizitka_paper.addItem("")
        self.vizitka_paper.addItem("")
        self.vizitka_paper.addItem("")
        self.vizitka_paper.addItem("")
        self.vizitka_paper.addItem("")
        self.vizitka_paper.addItem("")
        self.vizitka_paper.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.vizitka_paper)
        self.vizitka_colorful_label = QtWidgets.QLabel(self.SWPVizitki)
        self.vizitka_colorful_label.setObjectName("vizitka_colorful_label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.vizitka_colorful_label)
        self.vizitka_colorful = QtWidgets.QComboBox(self.SWPVizitki)
        self.vizitka_colorful.setObjectName("vizitka_colorful")
        self.vizitka_colorful.addItem("")
        self.vizitka_colorful.addItem("")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.vizitka_colorful)
        self.vizitka_col_label = QtWidgets.QLabel(self.SWPVizitki)
        self.vizitka_col_label.setObjectName("vizitka_col_label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.vizitka_col_label)
        self.vizitka_col = QtWidgets.QLineEdit(self.SWPVizitki)
        self.vizitka_col.setObjectName("vizitka_col")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.vizitka_col)
        self.vizitka_lamination_label = QtWidgets.QLabel(self.SWPVizitki)
        self.vizitka_lamination_label.setObjectName("vizitka_lamination_label")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.vizitka_lamination_label)
        self.vizitka_lamination = QtWidgets.QCheckBox(self.SWPVizitki)
        self.vizitka_lamination.setText("")
        self.vizitka_lamination.setObjectName("vizitka_lamination")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.vizitka_lamination)
        self.vizitka_rounding_label = QtWidgets.QLabel(self.SWPVizitki)
        self.vizitka_rounding_label.setObjectName("vizitka_rounding_label")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.vizitka_rounding_label)
        self.vizitka_rounding = QtWidgets.QCheckBox(self.SWPVizitki)
        self.vizitka_rounding.setText("")
        self.vizitka_rounding.setObjectName("vizitka_rounding")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.vizitka_rounding)
        self.vizitka_price_label = QtWidgets.QLabel(self.SWPVizitki)
        self.vizitka_price_label.setObjectName("vizitka_price_label")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.vizitka_price_label)
        self.vizitka_price = QtWidgets.QLabel(self.SWPVizitki)
        self.vizitka_price.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.vizitka_price.setObjectName("vizitka_price")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.vizitka_price)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(7, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.vizitka_pushButton = QtWidgets.QPushButton(self.SWPVizitki)
        self.vizitka_pushButton.setObjectName("vizitka_pushButton")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.vizitka_pushButton)
        self.vizitka_pricep1_label = QtWidgets.QLabel(self.SWPVizitki)
        self.vizitka_pricep1_label.setObjectName("vizitka_pricep1_label")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.vizitka_pricep1_label)
        self.vizitka_pricep1 = QtWidgets.QLabel(self.SWPVizitki)
        self.vizitka_pricep1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.vizitka_pricep1.setObjectName("vizitka_pricep1")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.vizitka_pricep1)
        self.stackedWidget.addWidget(self.SWPVizitki)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.group.currentIndexChanged['int'].connect(self.stackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Группа изделий:"))
        self.group.setItemText(1, _translate("MainWindow", "Визитки"))
        self.vizitka_papre_label.setText(_translate("MainWindow", "Бумага:"))
        self.vizitka_paper.setItemText(0, _translate("MainWindow", "Офсетная 80 гр."))
        self.vizitka_paper.setItemText(1, _translate("MainWindow", "Maxigloss 130гр."))
        self.vizitka_paper.setItemText(2, _translate("MainWindow", "Maxigloss 170гр./м.кв"))
        self.vizitka_paper.setItemText(3, _translate("MainWindow", "Delight gloss в упак C2S Art"))
        self.vizitka_paper.setItemText(4, _translate("MainWindow", "Arconvert"))
        self.vizitka_paper.setItemText(5, _translate("MainWindow", "Тач кавер 300"))
        self.vizitka_paper.setItemText(6, _translate("MainWindow", "ICELASER Лен"))
        self.vizitka_paper.setItemText(7, _translate("MainWindow", "Comet брилиант 300 гр."))
        self.vizitka_paper.setItemText(8, _translate("MainWindow", "Acquerello 300 гр."))
        self.vizitka_paper.setItemText(9, _translate("MainWindow", "Nettuno 300 гр."))
        self.vizitka_paper.setItemText(10, _translate("MainWindow", "Sirio pearl 300 гр."))
        self.vizitka_paper.setItemText(11, _translate("MainWindow", "Splendorgel 300 гр."))
        self.vizitka_paper.setItemText(12, _translate("MainWindow", "TintoRetto 300 гр."))
        self.vizitka_colorful_label.setText(_translate("MainWindow", "Цветность:"))
        self.vizitka_colorful.setItemText(0, _translate("MainWindow", "4+0"))
        self.vizitka_colorful.setItemText(1, _translate("MainWindow", "4+4"))
        self.vizitka_col_label.setText(_translate("MainWindow", "Тираж:"))
        self.vizitka_lamination_label.setText(_translate("MainWindow", "Ламинация:"))
        self.vizitka_rounding_label.setText(_translate("MainWindow", "Скругление углов:"))
        self.vizitka_price_label.setText(_translate("MainWindow", "Итоговая цена:"))
        self.vizitka_price.setText(_translate("MainWindow", "0"))
        self.vizitka_pushButton.setText(_translate("MainWindow", "Рассчитать"))
        self.vizitka_pricep1_label.setText(_translate("MainWindow", "Цена 1 листа бумаги:"))
        self.vizitka_pricep1.setText(_translate("MainWindow", "0"))


